# Generated by Django 5.0.6 on 2024-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_alter_publication_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="sub_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
